# Site settings
title: IMPACT - Start, Accelerate, Impact.
email: info@impact-accelerator.com
baseurl: ""
url: "http://www.impact-accelerator.com"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [Gruntfile.js, package.json, .less, bower_components, custom_components/custom/examples, custom_components/custom/less, node_modules]

prose:
#  rooturl: '_posts'
  media: 'assets'
  metadata:
    _posts/news:
      - name: "category"
        field:
          element: "hidden"
          value: "news"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa de la imagen"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Ingles"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Ingles"
              value: "en"
          selected: "en"
    _posts/team:
      - name: "category"
        field:
          element: "hidden"
          value: "equipo"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Nombre del colaborador"
          value: ""
      - name: "cargo"
        field:
          element: "text"
          label: "Cargo"
          value: ""
      - name: "cargo_impact_es"
        field:
          element: "text"
          label: "Cargo Impact (Castellano)"
          value: ""
      - name: "cargo_impact_en"
        field:
          element: "text"
          label: "Cargo Impact (Ingles)"
          value: ""
      - name: "linked-in"
        field:
          element: "text"
          label: "URL Linkedin"
          value: ""
      - name: "twitter"
        field:
          element: "text"
          label: "URL Twitter"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa a la imagen (350x350px)"
          value: ""
    _posts/mentors:
      - name: "category"
        field:
          element: "hidden"
          value: "mentor"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Nombre del colaborador"
          value: ""
      - name: "cargo"
        field:
          element: "text"
          label: "Cargo"
          value: ""
      - name: "cargo_impact_es"
        field:
          element: "text"
          label: "Cargo Impact (Castellano)"
          value: ""
      - name: "cargo_impact_en"
        field:
          element: "text"
          label: "Cargo Impact (Ingles)"
          value: ""
      - name: "linked-in"
        field:
          element: "text"
          label: "URL Linkedin"
          value: ""
      - name: "twitter"
        field:
          element: "text"
          label: "URL Twitter"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa a la imagen (350x350px)"
          value: ""
