# Site settings
title: Impact - Start. Accelerate. Impact.
email: info@impact.com
description: "Subvencionamos, Aceleramos e Invertimos en los Mejores Emprendimientos de Internet Mobile Ayudándoles a Generar Impacto Global."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
