title: IMPACT - Start, Accelerate, Impact.
email: info@impact-accelerator.com
baseurl: ""
url: "http://www.impact-accelerator.com"
markdown: kramdown
permalink: pretty
exclude: [Gruntfile.js, package.json, .less, bower_components, custom_components/custom/examples, custom_components/custom/less, node_modules]

prose:
  media: 'assets'
  metadata:
    _posts/news:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "news"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "image"
        field:
          element: "text"
          label: "URL relativa de la imagen"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Ingles"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Ingles"
              value: "en"
            - name: "Italian"
              value: "it"
          selected: "es"
    _posts/news/en:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "news"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa de la imagen"
      - name: "lang"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Ingles"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Ingles"
              value: "en"
            - name: "Italian"
              value: "it"
          selected: "en"
    _posts/news/it:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "news"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa de la imagen"
      - name: "lang"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Ingles"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Ingles"
              value: "en"
            - name: "Italian"
              value: "it"
          selected: "it"
    _posts/team:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "equipo"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Nombre del colaborador"
          value: ""
      - name: "cargo"
        field:
          element: "text"
          label: "Cargo"
          value: ""
      - name: "cargo_impact_es"
        field:
          element: "text"
          label: "Cargo Impact (Castellano)"
          value: ""
      - name: "cargo_impact_en"
        field:
          element: "text"
          label: "Cargo Impact (Ingles)"
          value: ""
      - name: "linked-in"
        field:
          element: "text"
          label: "URL Linkedin"
          value: ""
      - name: "twitter"
        field:
          element: "text"
          label: "URL Twitter"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa a la imagen (350x350px)"
          value: ""
    _posts/mentors:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "mentor"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Nombre del colaborador"
          value: ""
      - name: "cargo"
        field:
          element: "text"
          label: "Cargo (En su empresa, no se suele usar para mentores)."
          value: ""
      - name: "cargo_impact_es"
        field:
          element: "text"
          label: "Cargo Impact (Castellano)"
          value: ""
      - name: "cargo_impact_en"
        field:
          element: "text"
          label: "Cargo Impact (Ingles)"
          value: ""
      - name: "linked-in"
        field:
          element: "text"
          label: "URL Linkedin"
          value: ""
      - name: "twitter"
        field:
          element: "text"
          label: "URL Twitter"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa a la imagen (350x350px)"
          value: ""
      - name: "mentor_type"
        field:
          element: "multiselect"
          label: "Mentor type"
          options:
            - name: "Follow up Mentor"
              value: "follow_up"
            - name: "Specialized Mentor"
              value: "specialized"
      - name: "mentor_field"
        field:
          element: "multiselect"
          label: "Field of expertise"
          options:
            - name: "Strategy & Biz Model"
              value: "strategy"
            - name: "Marketing & Sales"
              value: "marketing"
            - name: "Product development"
              value: "product_development"
            - name: "Internationalization"
              value: "internationalization"
            - name: "Finance & Funding"
              value: "finance"
            - name: "Management"
              value: "management"
            - name: "Legal"
              value: "legal"
            - name: "Technology"
              value: "tech"
      - name: "mentor_country"
        field:
          element: "multiselect"
          label: "Country"
          options:
            - name: "Spain"
              value: "Spain"
            - name: "Italy"
              value: "Italy"
            - name: "Denmark"
              value: "Denmark"
            - name: "Poland"
              value: "Poland"
            - name: "UK"
              value: "UK"
            - name: "Germany"
              value: "Germany"