title: IMPACT - Start, Accelerate, Impact.
email: info@impact-accelerator.com
baseurl: ""
url: "http://www.impact-accelerator.com"
markdown: kramdown
permalink: pretty
exclude: [Gruntfile.js, package.json, .less, bower_components, custom_components/custom/examples, custom_components/custom/less, node_modules]

prose:
  media: 'assets'
  metadata:
    _posts/news:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "news"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "image"
        field:
          element: "text"
          label: "URL relativa de la imagen"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Ingles"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Ingles"
              value: "en"
            - name: "Italian"
              value: "it"
          value: "es"
    _posts/news/en:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "news"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa de la imagen"
      - name: "lang"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Ingles"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Ingles"
              value: "en"
            - name: "Italian"
              value: "it"
          value: "en"
    _posts/news/it:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "news"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa de la imagen"
      - name: "lang"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Ingles"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Ingles"
              value: "en"
            - name: "Italian"
              value: "it"
          value: "it"
    _posts/team:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "equipo"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Nombre del colaborador"
          value: ""
      - name: "cargo"
        field:
          element: "text"
          label: "Cargo"
          value: ""
      - name: "cargo_impact_es"
        field:
          element: "text"
          label: "Cargo Impact (Castellano)"
          value: ""
      - name: "cargo_impact_en"
        field:
          element: "text"
          label: "Cargo Impact (Ingles)"
          value: ""
      - name: "linked-in"
        field:
          element: "text"
          label: "URL Linkedin"
          value: ""
      - name: "twitter"
        field:
          element: "text"
          label: "URL Twitter"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa a la imagen (350x350px)"
          value: ""
    _posts/mentors:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "mentor"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Nombre del colaborador"
          value: ""
      - name: "cargo"
        field:
          element: "text"
          label: "Cargo (En su empresa, no se suele usar para mentores)."
          value: ""
      - name: "cargo_impact_es"
        field:
          element: "text"
          label: "Cargo Impact (Castellano)"
          value: ""
      - name: "cargo_impact_en"
        field:
          element: "text"
          label: "Cargo Impact (Ingles)"
          value: ""
      - name: "linked-in"
        field:
          element: "text"
          label: "URL Linkedin"
          value: ""
      - name: "twitter"
        field:
          element: "text"
          label: "URL Twitter"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa a la imagen (350x350px)"
          value: ""
      - name: "mentor_type"
        field:
          element: "multiselect"
          label: "Mentor type"
          options:
            - name: "Follow up Mentor"
              value: "follow_up"
            - name: "Specialized Mentor"
              value: "specialized"
      - name: "mentor_field"
        field:
          element: "multiselect"
          label: "Field of expertise"
          options:
            - name: "Strategy & Biz Model"
              value: "strategy"
            - name: "Marketing & Sales"
              value: "marketing"
            - name: "Product development"
              value: "product_development"
            - name: "Internationalization"
              value: "internationalization"
            - name: "Finance & Funding"
              value: "finance"
            - name: "Management"
              value: "management"
            - name: "Legal"
              value: "legal"
            - name: "Technology"
              value: "tech"
      - name: "mentor_country"
        field:
          element: "multiselect"
          label: "Country"
          options:
            - name: "Spain"
              value: "Spain"
            - name: "Italy"
              value: "Italy"
            - name: "Denmark"
              value: "Denmark"
            - name: "Poland"
              value: "Poland"
            - name: "UK"
              value: "UK"
            - name: "Germany"
              value: "Germany"
    _posts/portfolio:
      - name: "category"
        field:
          label: "Categoría"
          element: "text"
          value: "portfolio"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Nombre Empresa"
          value: ""
      - name: "desc"
        field:
          element: "text"
          label: "Entradilla en castellano."
          value: ""
      - name: "desc_en"
        field:
          element: "text"
          label: "Entradilla en Ingles."
          value: ""
      - name: "desc_it"
        field:
          element: "text"
          label: "Entradilla en Italiano."
          value: ""
      - name: "web"
        field:
          element: "text"
          label: "URL de página web (incluir http://)"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "URL relativa a la imagen (300x300px)"
          value: ""
      - name: "sector"
        field:
          element: "multiselect"
          label: "Sector"
          options:
            - name: "CTV" 
              value: "CTV"
            - name: "Deporte" 
              value: "Deporte"
            - name: "Diseño" 
              value: "Diseno"
            - name: "Educación" 
              value: "Educacion"
            - name: "Eventos" 
              value: "Eventos"
            - name: "Fotografias" 
              value: "Fotografias"
            - name: "Futbol" 
              value: "Futbol"
            - name: "Horeca" 
              value: "Horeca"
            - name: "Medios" 
              value: "Medios"
            - name: "Moda" 
              value: "Moda"
            - name: "Musica" 
              value: "Musica"
            - name: "Navegación" 
              value: "Navegacion"
            - name: "Pagos" 
              value: "Pagos"
            - name: "Productividad" 
              value: "Productividad"
            - name: "Restauración" 
              value: "Restauracion"
            - name: "Salud" 
              value: "Salud"
            - name: "Social"  
              value: "Social" 
            - name: "Técnología móvil" 
              value: "TecnologiaMovil"
            - name: "Telecomunicaciones"
               value: "Telecomunicaciones"
            - name: "Viajes" 
              value: "Viajes"
      - name: "bussiness"
        field:
          element: "multiselect"
          label: "Type Of Business"
          options:
            - name: "App"  
              value: "App" 
            - name: "E-commerce" 
              value: "E-commerce"
            - name: "Fremium" 
              value: "Fremium"
            - name: "Marketplace" 
              value: "Marketplace"
            - name: "SaaS" 
              value: "SaaS"
            - name: "Service" 
              value: "Service"
            - name: "Servicios" 
              value: "Servicios"
      - name: "model"
        field:
          element: "multiselect"
          label: "Business Model"
          options:
            - name: "B2C"
              value: "B2C" 
            - name: "B2B"
              value: "B2B"
      - name: "mentor_country"
        field:
          element: "multiselect"
          label: "Country"
          options:
            - name: "Spain"
              value: "Spain"
            - name: "Italy"
              value: "Italy"
            - name: "Denmark"
              value: "Denmark"
            - name: "Poland"
              value: "Poland"
            - name: "UK"
              value: "UK"
            - name: "Germany"
              value: "Germany" 
            - name: "Holland"
              value: "Holland"
            - name: "Slovenia"
              value: "Slovenia"